config/routes.rb
Rails.application.routes.draw do
  root to: 'home#index'

  resources :announcements, only: :create
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/announcements_controller.rb
class AnnouncementsController < ApplicationController
  def create
    50.times do
      `/usr/bin/amixer -q set Master 1%-`
      sleep 0.02
    end

    `/usr/bin/omxplayer -o local /home/pi/echo/start-#{params[:start]}.mp3`

    50.times do
      `/usr/bin/amixer -q set Master 1%+`
      sleep 0.02
    end

    redirect_to root_path
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/index.html.slim
.uk-container class="uk-width-1-3@m"
  .uk-text-center.uk-margin-bottom
    = image_pack_tag 'crossecho.png', style: 'height: 200px;'
  .uk-card.uk-card-default.uk-background-secondary.uk-light
    .uk-card-header.uk-light.uk-text-center
      h3 Foyer announcements
    .uk-card-body.uk-flex.uk-flex-column.uk-flex-center
      = link_to 'ZACZYNAMY ZA 5 MIN.', announcements_path(start: 5), method: :post, class: 'uk-button uk-button-default uk-width-1-1', data: { disable_with: '▶ ▶ ▶' }
      br
      br
      = link_to 'ZACZYNAMY ZA 1 MIN.', announcements_path(start: 0), method: :post, class: 'uk-button uk-button-default uk-width-1-1', data: { disable_with: '▶ ▶ ▶' }

app/views/layouts/application.html.slim
doctype html
html
  head
    title Foyer announcements
    meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no"
    = csrf_meta_tags
    = csp_meta_tag

    = javascript_pack_tag 'application'
    = stylesheet_pack_tag 'application'
    = favicon_pack_tag 'fav.png'

  body.uk-flex.uk-flex-center.uk-flex-middle.uk-height-viewport style="background-color: #262626;"
    = yield